# -*- coding: utf-8 -*-
"""reverse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZe7YrYHoDJU7e6aO5DZJ59YvqVPGlb_
"""

m = [[1, 2], [3, 4], [5, 6, 7]]
m.reverse()
for l in m:
  l.reverse()
print(m)